// Generated by gencpp from file service_pkg/CustomServMess.msg
// DO NOT EDIT!


#ifndef SERVICE_PKG_MESSAGE_CUSTOMSERVMESS_H
#define SERVICE_PKG_MESSAGE_CUSTOMSERVMESS_H

#include <ros/service_traits.h>


#include <service_pkg/CustomServMessRequest.h>
#include <service_pkg/CustomServMessResponse.h>


namespace service_pkg
{

struct CustomServMess
{

typedef CustomServMessRequest Request;
typedef CustomServMessResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CustomServMess
} // namespace service_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_pkg::CustomServMess > {
  static const char* value()
  {
    return "b92c952a9248b3029cefe45f52f6ffde";
  }

  static const char* value(const ::service_pkg::CustomServMess&) { return value(); }
};

template<>
struct DataType< ::service_pkg::CustomServMess > {
  static const char* value()
  {
    return "service_pkg/CustomServMess";
  }

  static const char* value(const ::service_pkg::CustomServMess&) { return value(); }
};


// service_traits::MD5Sum< ::service_pkg::CustomServMessRequest> should match
// service_traits::MD5Sum< ::service_pkg::CustomServMess >
template<>
struct MD5Sum< ::service_pkg::CustomServMessRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_pkg::CustomServMess >::value();
  }
  static const char* value(const ::service_pkg::CustomServMessRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_pkg::CustomServMessRequest> should match
// service_traits::DataType< ::service_pkg::CustomServMess >
template<>
struct DataType< ::service_pkg::CustomServMessRequest>
{
  static const char* value()
  {
    return DataType< ::service_pkg::CustomServMess >::value();
  }
  static const char* value(const ::service_pkg::CustomServMessRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_pkg::CustomServMessResponse> should match
// service_traits::MD5Sum< ::service_pkg::CustomServMess >
template<>
struct MD5Sum< ::service_pkg::CustomServMessResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_pkg::CustomServMess >::value();
  }
  static const char* value(const ::service_pkg::CustomServMessResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_pkg::CustomServMessResponse> should match
// service_traits::DataType< ::service_pkg::CustomServMess >
template<>
struct DataType< ::service_pkg::CustomServMessResponse>
{
  static const char* value()
  {
    return DataType< ::service_pkg::CustomServMess >::value();
  }
  static const char* value(const ::service_pkg::CustomServMessResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_PKG_MESSAGE_CUSTOMSERVMESS_H
