// Generated by gencpp from file service_pkg/CustomServMessResponse.msg
// DO NOT EDIT!


#ifndef SERVICE_PKG_MESSAGE_CUSTOMSERVMESSRESPONSE_H
#define SERVICE_PKG_MESSAGE_CUSTOMSERVMESSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace service_pkg
{
template <class ContainerAllocator>
struct CustomServMessResponse_
{
  typedef CustomServMessResponse_<ContainerAllocator> Type;

  CustomServMessResponse_()
    : success(false)  {
    }
  CustomServMessResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::service_pkg::CustomServMessResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::service_pkg::CustomServMessResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CustomServMessResponse_

typedef ::service_pkg::CustomServMessResponse_<std::allocator<void> > CustomServMessResponse;

typedef boost::shared_ptr< ::service_pkg::CustomServMessResponse > CustomServMessResponsePtr;
typedef boost::shared_ptr< ::service_pkg::CustomServMessResponse const> CustomServMessResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::service_pkg::CustomServMessResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::service_pkg::CustomServMessResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::service_pkg::CustomServMessResponse_<ContainerAllocator1> & lhs, const ::service_pkg::CustomServMessResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::service_pkg::CustomServMessResponse_<ContainerAllocator1> & lhs, const ::service_pkg::CustomServMessResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace service_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::service_pkg::CustomServMessResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_pkg::CustomServMessResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_pkg::CustomServMessResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_pkg::CustomServMessResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_pkg::CustomServMessResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_pkg::CustomServMessResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::service_pkg::CustomServMessResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::service_pkg::CustomServMessResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::service_pkg::CustomServMessResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "service_pkg/CustomServMessResponse";
  }

  static const char* value(const ::service_pkg::CustomServMessResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::service_pkg::CustomServMessResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
"\n"
;
  }

  static const char* value(const ::service_pkg::CustomServMessResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::service_pkg::CustomServMessResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomServMessResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::service_pkg::CustomServMessResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::service_pkg::CustomServMessResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVICE_PKG_MESSAGE_CUSTOMSERVMESSRESPONSE_H
