// Generated by gencpp from file service_pkg/CustomServMessRequest.msg
// DO NOT EDIT!


#ifndef SERVICE_PKG_MESSAGE_CUSTOMSERVMESSREQUEST_H
#define SERVICE_PKG_MESSAGE_CUSTOMSERVMESSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace service_pkg
{
template <class ContainerAllocator>
struct CustomServMessRequest_
{
  typedef CustomServMessRequest_<ContainerAllocator> Type;

  CustomServMessRequest_()
    : duration(0)  {
    }
  CustomServMessRequest_(const ContainerAllocator& _alloc)
    : duration(0)  {
  (void)_alloc;
    }



   typedef int32_t _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::service_pkg::CustomServMessRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::service_pkg::CustomServMessRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CustomServMessRequest_

typedef ::service_pkg::CustomServMessRequest_<std::allocator<void> > CustomServMessRequest;

typedef boost::shared_ptr< ::service_pkg::CustomServMessRequest > CustomServMessRequestPtr;
typedef boost::shared_ptr< ::service_pkg::CustomServMessRequest const> CustomServMessRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::service_pkg::CustomServMessRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::service_pkg::CustomServMessRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::service_pkg::CustomServMessRequest_<ContainerAllocator1> & lhs, const ::service_pkg::CustomServMessRequest_<ContainerAllocator2> & rhs)
{
  return lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::service_pkg::CustomServMessRequest_<ContainerAllocator1> & lhs, const ::service_pkg::CustomServMessRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace service_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::service_pkg::CustomServMessRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_pkg::CustomServMessRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_pkg::CustomServMessRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_pkg::CustomServMessRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_pkg::CustomServMessRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_pkg::CustomServMessRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::service_pkg::CustomServMessRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f60182c6a4cf2e688b1837c24d5f12e";
  }

  static const char* value(const ::service_pkg::CustomServMessRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f60182c6a4cf2e6ULL;
  static const uint64_t static_value2 = 0x88b1837c24d5f12eULL;
};

template<class ContainerAllocator>
struct DataType< ::service_pkg::CustomServMessRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "service_pkg/CustomServMessRequest";
  }

  static const char* value(const ::service_pkg::CustomServMessRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::service_pkg::CustomServMessRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 duration\n"
;
  }

  static const char* value(const ::service_pkg::CustomServMessRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::service_pkg::CustomServMessRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomServMessRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::service_pkg::CustomServMessRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::service_pkg::CustomServMessRequest_<ContainerAllocator>& v)
  {
    s << indent << "duration: ";
    Printer<int32_t>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVICE_PKG_MESSAGE_CUSTOMSERVMESSREQUEST_H
